package jeffersonmca.com.github.gerenciadorambiente.visao;

import jeffersonmca.com.github.gerenciadorambiente.visao.ambiente.AmbienteListagem;
import jeffersonmca.com.github.gerenciadorambiente.visao.aula.AulaListagem;
import jeffersonmca.com.github.gerenciadorambiente.visao.curso.CursoListagem;
import jeffersonmca.com.github.gerenciadorambiente.visao.disciplina.DisciplinaListagem;
import jeffersonmca.com.github.gerenciadorambiente.visao.periodo.PeriodoListagem;
import jeffersonmca.com.github.gerenciadorambiente.visao.pessoa.PessoaListagem;
import jeffersonmca.com.github.gerenciadorambiente.visao.turma.TurmaListagem;

public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadMenuAmbiente = new javax.swing.JMenuItem();
        cadMenuAula = new javax.swing.JMenuItem();
        cadMenuCurso = new javax.swing.JMenuItem();
        cadMenuDisciplina = new javax.swing.JMenuItem();
        cadMenuPeriodo = new javax.swing.JMenuItem();
        cadMenuPessoa = new javax.swing.JMenuItem();
        cadMenuTurma = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        pesMenuAmbiente = new javax.swing.JMenuItem();
        pesMenuAula = new javax.swing.JMenuItem();
        pesMenuCurso = new javax.swing.JMenuItem();
        pesMenuDisciplina = new javax.swing.JMenuItem();
        pesMenuPeriodo = new javax.swing.JMenuItem();
        pesMenuPessoa = new javax.swing.JMenuItem();
        pesMenuTurma = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        relMenuAmbiente = new javax.swing.JMenuItem();
        relMenuAula = new javax.swing.JMenuItem();
        relMenuCurso = new javax.swing.JMenuItem();
        relMenuDisciplina = new javax.swing.JMenuItem();
        relMenuPeriodo = new javax.swing.JMenuItem();
        relMenuPessoa = new javax.swing.JMenuItem();
        relMenuTurma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro");

        cadMenuAmbiente.setText("Ambiente");
        cadMenuAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMenuAmbienteActionPerformed(evt);
            }
        });
        jMenu1.add(cadMenuAmbiente);

        cadMenuAula.setText("Aula");
        cadMenuAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMenuAulaActionPerformed(evt);
            }
        });
        jMenu1.add(cadMenuAula);

        cadMenuCurso.setText("Curso");
        cadMenuCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMenuCursoActionPerformed(evt);
            }
        });
        jMenu1.add(cadMenuCurso);

        cadMenuDisciplina.setText("Disciplina");
        cadMenuDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMenuDisciplinaActionPerformed(evt);
            }
        });
        jMenu1.add(cadMenuDisciplina);

        cadMenuPeriodo.setText("Período");
        cadMenuPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMenuPeriodoActionPerformed(evt);
            }
        });
        jMenu1.add(cadMenuPeriodo);

        cadMenuPessoa.setText("Pessoa");
        cadMenuPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMenuPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(cadMenuPessoa);

        cadMenuTurma.setText("Turma");
        cadMenuTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMenuTurmaActionPerformed(evt);
            }
        });
        jMenu1.add(cadMenuTurma);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Pesquisa");

        pesMenuAmbiente.setText("Ambiente");
        jMenu3.add(pesMenuAmbiente);

        pesMenuAula.setText("Aula");
        jMenu3.add(pesMenuAula);

        pesMenuCurso.setText("Curso");
        jMenu3.add(pesMenuCurso);

        pesMenuDisciplina.setText("Disciplina");
        jMenu3.add(pesMenuDisciplina);

        pesMenuPeriodo.setText("Periodo");
        jMenu3.add(pesMenuPeriodo);

        pesMenuPessoa.setText("Pessoa");
        jMenu3.add(pesMenuPessoa);

        pesMenuTurma.setText("Turma");
        jMenu3.add(pesMenuTurma);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Relatório");

        relMenuAmbiente.setText("Ambiente");
        relMenuAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relMenuAmbienteActionPerformed(evt);
            }
        });
        jMenu2.add(relMenuAmbiente);

        relMenuAula.setText("Aula");
        jMenu2.add(relMenuAula);

        relMenuCurso.setText("Curso");
        jMenu2.add(relMenuCurso);

        relMenuDisciplina.setText("Disciplina");
        jMenu2.add(relMenuDisciplina);

        relMenuPeriodo.setText("Período");
        jMenu2.add(relMenuPeriodo);

        relMenuPessoa.setText("Pessoa");
        jMenu2.add(relMenuPessoa);

        relMenuTurma.setText("Turma");
        jMenu2.add(relMenuTurma);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadMenuAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMenuAmbienteActionPerformed
        AmbienteListagem tela = new AmbienteListagem();
        tela.setVisible(true);
    }//GEN-LAST:event_cadMenuAmbienteActionPerformed

    private void cadMenuAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMenuAulaActionPerformed
        AulaListagem tela = new AulaListagem();
        tela.setVisible(true);
    }//GEN-LAST:event_cadMenuAulaActionPerformed

    private void cadMenuCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMenuCursoActionPerformed
        CursoListagem tela = new CursoListagem();
        tela.setVisible(true);
    }//GEN-LAST:event_cadMenuCursoActionPerformed

    private void cadMenuDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMenuDisciplinaActionPerformed
        DisciplinaListagem tela = new DisciplinaListagem();
        tela.setVisible(true);
    }//GEN-LAST:event_cadMenuDisciplinaActionPerformed

    private void cadMenuPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMenuPeriodoActionPerformed
        PeriodoListagem tela = new PeriodoListagem();
        tela.setVisible(true);
    }//GEN-LAST:event_cadMenuPeriodoActionPerformed

    private void cadMenuPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMenuPessoaActionPerformed
        PessoaListagem tela = new PessoaListagem();
        tela.setVisible(true);
    }//GEN-LAST:event_cadMenuPessoaActionPerformed

    private void cadMenuTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMenuTurmaActionPerformed
        TurmaListagem tela = new TurmaListagem();
        tela.setVisible(true);
    }//GEN-LAST:event_cadMenuTurmaActionPerformed

    private void relMenuAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relMenuAmbienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relMenuAmbienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadMenuAmbiente;
    private javax.swing.JMenuItem cadMenuAula;
    private javax.swing.JMenuItem cadMenuCurso;
    private javax.swing.JMenuItem cadMenuDisciplina;
    private javax.swing.JMenuItem cadMenuPeriodo;
    private javax.swing.JMenuItem cadMenuPessoa;
    private javax.swing.JMenuItem cadMenuTurma;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem pesMenuAmbiente;
    private javax.swing.JMenuItem pesMenuAula;
    private javax.swing.JMenuItem pesMenuCurso;
    private javax.swing.JMenuItem pesMenuDisciplina;
    private javax.swing.JMenuItem pesMenuPeriodo;
    private javax.swing.JMenuItem pesMenuPessoa;
    private javax.swing.JMenuItem pesMenuTurma;
    private javax.swing.JMenuItem relMenuAmbiente;
    private javax.swing.JMenuItem relMenuAula;
    private javax.swing.JMenuItem relMenuCurso;
    private javax.swing.JMenuItem relMenuDisciplina;
    private javax.swing.JMenuItem relMenuPeriodo;
    private javax.swing.JMenuItem relMenuPessoa;
    private javax.swing.JMenuItem relMenuTurma;
    // End of variables declaration//GEN-END:variables
}