package jeffersonmca.com.github.gerenciadorambiente.visao;

import java.awt.Cursor;

public class VisaoLogin extends javax.swing.JFrame {

    public VisaoLogin() {        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformacoes = new javax.swing.JPanel();
        labelSenha = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        passwordSenha = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        labelRecebimento = new javax.swing.JLabel();
        panelBotoes = new javax.swing.JPanel();
        buttonSenha = new javax.swing.JButton();
        buttonEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        panelInformacoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInformacoes.setLayout(null);

        labelSenha.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        labelSenha.setText("Senha:");
        labelSenha.setName("labelUsuario"); // NOI18N
        panelInformacoes.add(labelSenha);
        labelSenha.setBounds(20, 60, 90, 26);

        labelUsuario.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        labelUsuario.setText("Usuário:");
        labelUsuario.setName(""); // NOI18N
        panelInformacoes.add(labelUsuario);
        labelUsuario.setBounds(20, 30, 90, 26);
        panelInformacoes.add(textUsuario);
        textUsuario.setBounds(110, 30, 190, 27);
        panelInformacoes.add(passwordSenha);
        passwordSenha.setBounds(110, 60, 190, 27);

        getContentPane().add(panelInformacoes);
        panelInformacoes.setBounds(0, 220, 350, 100);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        labelRecebimento.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        labelRecebimento.setText("Bem Vindo!");
        jPanel1.add(labelRecebimento);
        labelRecebimento.setBounds(100, 100, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 220);

        panelBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotoes.setLayout(null);

        buttonSenha.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        buttonSenha.setText("Sair");
        buttonSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSenhaMouseExited(evt);
            }
        });
        panelBotoes.add(buttonSenha);
        buttonSenha.setBounds(190, 10, 60, 40);

        buttonEntrar.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        buttonEntrar.setText("Entrar");
        buttonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEntrarMouseExited(evt);
            }
        });
        panelBotoes.add(buttonEntrar);
        buttonEntrar.setBounds(250, 10, 90, 40);

        getContentPane().add(panelBotoes);
        panelBotoes.setBounds(0, 320, 350, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEntrarMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_buttonEntrarMouseExited

    private void buttonEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEntrarMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_buttonEntrarMouseEntered

    private void buttonSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSenhaMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_buttonSenhaMouseEntered

    private void buttonSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSenhaMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_buttonSenhaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaoLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEntrar;
    private javax.swing.JButton buttonSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelRecebimento;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelInformacoes;
    private javax.swing.JPasswordField passwordSenha;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
