package jeffersonmca.com.github.gerenciadorambiente.visao;

import java.awt.Cursor;
import javax.swing.UIManager;
import jeffersonmca.com.github.gerenciadorambiente.servico.ServicoAmbiente;
import jeffersonmca.com.github.gerenciadorambiente.util.Conexao;

public class VisaoLogin extends javax.swing.JFrame {

    public VisaoLogin() {
        
        initComponents();
        //Conexao.getConexao();
        ServicoAmbiente servico = new ServicoAmbiente();
        
        try {
         //   servico.buscarPorCodigo(1);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformacoes = new javax.swing.JPanel();
        labelSenha = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        passwordSenha = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        labelRecebimento = new javax.swing.JLabel();
        panelBotoes = new javax.swing.JPanel();
        buttonSair = new javax.swing.JButton();
        buttonEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        panelInformacoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInformacoes.setLayout(null);

        labelSenha.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        labelSenha.setText("Senha:");
        labelSenha.setName("labelUsuario"); // NOI18N
        panelInformacoes.add(labelSenha);
        labelSenha.setBounds(20, 60, 90, 26);

        labelUsuario.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        labelUsuario.setText("Usuário:");
        labelUsuario.setName(""); // NOI18N
        panelInformacoes.add(labelUsuario);
        labelUsuario.setBounds(20, 30, 90, 26);
        panelInformacoes.add(textUsuario);
        textUsuario.setBounds(110, 30, 190, 27);
        panelInformacoes.add(passwordSenha);
        passwordSenha.setBounds(110, 60, 190, 27);

        getContentPane().add(panelInformacoes);
        panelInformacoes.setBounds(0, 220, 350, 100);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        labelRecebimento.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        labelRecebimento.setText("Bem Vindo!");
        jPanel1.add(labelRecebimento);
        labelRecebimento.setBounds(100, 100, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 220);

        panelBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotoes.setLayout(null);

        buttonSair.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        buttonSair.setText("Sair");
        buttonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSairMouseExited(evt);
            }
        });
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });
        panelBotoes.add(buttonSair);
        buttonSair.setBounds(190, 10, 60, 40);

        buttonEntrar.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        buttonEntrar.setText("Entrar");
        buttonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEntrarMouseExited(evt);
            }
        });
        buttonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrarActionPerformed(evt);
            }
        });
        panelBotoes.add(buttonEntrar);
        buttonEntrar.setBounds(250, 10, 90, 40);

        getContentPane().add(panelBotoes);
        panelBotoes.setBounds(0, 320, 350, 60);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEntrarMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_buttonEntrarMouseExited

    private void buttonEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEntrarMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_buttonEntrarMouseEntered

    private void buttonSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSairMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_buttonSairMouseEntered

    private void buttonSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSairMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_buttonSairMouseExited

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEntrarActionPerformed
        
        //Login login = new Login();
        Principal telaPrincipal = new Principal();
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_buttonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {          
            UIManager.setLookAndFeel(            
                    UIManager.getSystemLookAndFeelClassName()
            );
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaoLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEntrar;
    private javax.swing.JButton buttonSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelRecebimento;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelInformacoes;
    private javax.swing.JPasswordField passwordSenha;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}